package dev.abstratium.abstrauth.boundary;

import dev.abstratium.abstrauth.entity.OAuthClient;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import org.jboss.logging.Logger;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Test-only endpoint to observe SQL generated by Hibernate discriminator-based multi-tenancy.
 * This resource is in src/test/java so it is NOT included in production builds.
 */
@Path("/test/mt-sql-debug")
@Produces(MediaType.APPLICATION_JSON)
public class MultiTenancySqlDebugResource {

    private static final Logger LOG = Logger.getLogger(MultiTenancySqlDebugResource.class);

    @Inject
    EntityManager em;

    @POST
    @Path("/run-all")
    @Transactional
    public Response runAll(@HeaderParam("X-Org-Id") String orgId) {
        StringBuilder report = new StringBuilder();

        // Ensure the organisation row exists for the tenant (FK constraint on T_oauth_clients.org_id)
        if (orgId != null && !orgId.isBlank()) {
            em.createNativeQuery(
                    "MERGE INTO T_organisations (id, name, created_at) KEY(id) VALUES (:id, :name, CURRENT_TIMESTAMP)")
                    .setParameter("id", orgId)
                    .setParameter("name", "Test Org " + orgId.substring(0, 8))
                    .executeUpdate();
            em.flush();
            LOG.info("============================================================");
            LOG.info("=== ENSURED ORG EXISTS: " + orgId + " ===");
            LOG.info("============================================================");
        }

        // ============================================================
        // 1. CREATE (persist)
        // ============================================================
        OAuthClient client = new OAuthClient();
        String id = UUID.randomUUID().toString();
        client.setId(id);
        client.setClientId("debug-client-" + id.substring(0, 8));
        client.setClientName("SQL Debug Test Client");
        client.setClientType("confidential");
        client.setRedirectUris("[\"http://localhost/callback\"]");
        client.setAllowedScopes("[\"openid\",\"profile\"]");
        client.setRequirePkce(true);
        client.setAutoSubscribe(false);
        client.setCreatedAt(LocalDateTime.now());

        LOG.info("============================================================");
        LOG.info("=== ABOUT TO PERSIST (INSERT) OAuthClient id=" + id + " ===");
        LOG.info("============================================================");
        em.persist(client);
        em.flush();
        LOG.info("============================================================");
        LOG.info("=== PERSIST (INSERT) COMPLETE                            ===");
        LOG.info("============================================================");

        report.append("PERSIST done for id=").append(id).append("\n");

        // ============================================================
        // 2. SELECT by ID (em.find)
        // ============================================================
        LOG.info("============================================================");
        LOG.info("=== CLEARING PERSISTENCE CONTEXT TO FORCE DB ROUND-TRIP ===");
        LOG.info("============================================================");
        em.clear(); // Force em.find() to hit the database
        LOG.info("============================================================");
        LOG.info("=== ABOUT TO em.find(OAuthClient, id) ===");
        LOG.info("============================================================");
        OAuthClient found = em.find(OAuthClient.class, id);
        LOG.info("============================================================");
        LOG.info("=== em.find COMPLETE - found=" + (found != null) + " ===");
        LOG.info("============================================================");

        report.append("FIND done, found=").append(found != null).append("\n");

        // ============================================================
        // 3. SELECT with JPQL WHERE id = ?
        // ============================================================
        LOG.info("============================================================");
        LOG.info("=== ABOUT TO JPQL SELECT WHERE id = :id ===");
        LOG.info("============================================================");
        List<OAuthClient> results = em.createQuery(
                "SELECT c FROM OAuthClient c WHERE c.id = :id", OAuthClient.class)
                .setParameter("id", id)
                .getResultList();
        LOG.info("============================================================");
        LOG.info("=== JPQL SELECT COMPLETE - results.size()=" + results.size() + " ===");
        LOG.info("============================================================");

        report.append("JPQL SELECT done, count=").append(results.size()).append("\n");

        // ============================================================
        // 4. UPDATE via entity modification + flush
        // ============================================================
        LOG.info("============================================================");
        LOG.info("=== ABOUT TO UPDATE (modify + flush) ===");
        LOG.info("============================================================");
        found.setClientName("Updated SQL Debug Client");
        em.flush();
        LOG.info("============================================================");
        LOG.info("=== UPDATE COMPLETE                                      ===");
        LOG.info("============================================================");

        report.append("UPDATE done\n");

        // ============================================================
        // 5. UPDATE via JPQL UPDATE WHERE id = ?
        // ============================================================
        LOG.info("============================================================");
        LOG.info("=== ABOUT TO JPQL UPDATE WHERE id = :id ===");
        LOG.info("============================================================");
        int updatedCount = em.createQuery(
                "UPDATE OAuthClient c SET c.clientName = :name WHERE c.id = :id")
                .setParameter("name", "JPQL Updated Client")
                .setParameter("id", id)
                .executeUpdate();
        LOG.info("============================================================");
        LOG.info("=== JPQL UPDATE COMPLETE - updatedCount=" + updatedCount + " ===");
        LOG.info("============================================================");

        report.append("JPQL UPDATE done, updatedCount=").append(updatedCount).append("\n");

        // ============================================================
        // 6. DELETE via em.remove
        // ============================================================
        // Re-fetch after JPQL update to get managed entity
        OAuthClient toDelete = em.find(OAuthClient.class, id);
        LOG.info("============================================================");
        LOG.info("=== ABOUT TO em.remove (DELETE) ===");
        LOG.info("============================================================");
        em.remove(toDelete);
        em.flush();
        LOG.info("============================================================");
        LOG.info("=== em.remove (DELETE) COMPLETE                          ===");
        LOG.info("============================================================");

        report.append("DELETE done\n");

        // ============================================================
        // 7. DELETE via JPQL (on a new entity)
        // ============================================================
        OAuthClient client2 = new OAuthClient();
        String id2 = UUID.randomUUID().toString();
        client2.setId(id2);
        client2.setClientId("debug-client2-" + id2.substring(0, 8));
        client2.setClientName("Second Debug Client");
        client2.setClientType("confidential");
        client2.setRedirectUris("[\"http://localhost/callback2\"]");
        client2.setAllowedScopes("[\"openid\"]");
        client2.setRequirePkce(false);
        client2.setAutoSubscribe(true);
        client2.setCreatedAt(LocalDateTime.now());
        em.persist(client2);
        em.flush();

        LOG.info("============================================================");
        LOG.info("=== ABOUT TO JPQL DELETE WHERE id = :id ===");
        LOG.info("============================================================");
        int deletedCount = em.createQuery(
                "DELETE FROM OAuthClient c WHERE c.id = :id")
                .setParameter("id", id2)
                .executeUpdate();
        LOG.info("============================================================");
        LOG.info("=== JPQL DELETE COMPLETE - deletedCount=" + deletedCount + " ===");
        LOG.info("============================================================");

        report.append("JPQL DELETE done, deletedCount=").append(deletedCount).append("\n");

        LOG.info("============================================================");
        LOG.info("=== ALL OPERATIONS COMPLETE ===");
        LOG.info("============================================================");

        return Response.ok(report.toString()).build();
    }
}
