package dev.abstratium.abstrauth.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import dev.abstratium.abstrauth.entity.Account;
import dev.abstratium.abstrauth.util.TestDatabaseResetHelper;
import dev.abstratium.abstrauth.util.TestTransactionHelper;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;

/**
 * Tests for the scheduled audit purge service.
 */
@QuarkusTest
public class AuditPurgeServiceTest {

    @Inject
    AuditPurgeService auditPurgeService;

    @Inject
    AccountService accountService;

    @Inject
    EntityManager em;

    @Inject
    TestTransactionHelper transactionHelper;

    @Inject
    TestDatabaseResetHelper dbResetHelper;

    @BeforeEach
    public void resetDatabaseBeforeTest() throws Exception {
        transactionHelper.beginTransaction();
        dbResetHelper.resetDatabase();
        transactionHelper.commitTransaction();
    }

    @Test
    public void testPurgeRemovesOldAuditRowsAndOrphanedRevInfo() throws Exception {
        // Create a first account whose audit rows will be backdated.
        transactionHelper.beginTransaction();
        Account oldAccount = accountService.createAccountForOrg(
                "old_" + System.currentTimeMillis() + "@example.com",
                "Old Account",
                "old" + System.currentTimeMillis(),
                "Pass123",
                AccountService.NATIVE,
                getDefaultOrgId());
        String oldAccountId = oldAccount.getId();
        transactionHelper.commitTransaction();

        // Backdate all REVINFO rows generated by the first account.
        transactionHelper.beginTransaction();
        long oldTimestamp = Instant.now().minus(2, ChronoUnit.DAYS).toEpochMilli();
        @SuppressWarnings("unchecked")
        List<Number> oldRevs = em.createNativeQuery(
                "SELECT REV FROM REVINFO WHERE REVTSTMP >= :start")
                .setParameter("start", Instant.now().minus(1, ChronoUnit.HOURS).toEpochMilli())
                .getResultList();
        assertTrue(!oldRevs.isEmpty(), "Expected audit rows for the first account");
        em.createNativeQuery("UPDATE REVINFO SET REVTSTMP = :oldTimestamp WHERE REV IN :revs")
                .setParameter("oldTimestamp", oldTimestamp)
                .setParameter("revs", oldRevs)
                .executeUpdate();
        transactionHelper.commitTransaction();

        // Create a second account whose audit rows should remain after the purge.
        transactionHelper.beginTransaction();
        Account recentAccount = accountService.createAccountForOrg(
                "recent_" + System.currentTimeMillis() + "@example.com",
                "Recent Account",
                "recent" + System.currentTimeMillis(),
                "Pass123",
                AccountService.NATIVE,
                getDefaultOrgId());
        String recentAccountId = recentAccount.getId();
        transactionHelper.commitTransaction();

        // Run the purge with a 1-day retention period.
        AuditPurgeService.AuditPurgeResult result = auditPurgeService.purgeAuditData(1);

        // Verify the result metadata.
        assertEquals(1, result.getRetentionDays());
        assertTrue(result.getCutoffTimestamp() < Instant.now().toEpochMilli());
        assertTrue(result.getCutoffTimestamp() > oldTimestamp,
                "Cutoff should be between the old timestamp and now");

        long deletedFromAuditTables = result.getDeletedByTable().values().stream()
                .mapToLong(v -> v.longValue()).sum();
        assertTrue(deletedFromAuditTables > 0,
                "Expected at least one old audit row to be deleted");
        assertTrue(result.getDeletedRevInfoCount() > 0,
                "Expected at least one orphaned REVINFO row to be deleted");
        assertTrue(result.getTotalDeleted() >= deletedFromAuditTables + result.getDeletedRevInfoCount());

        // Verify old account audit rows are gone.
        transactionHelper.beginTransaction();
        long oldAccountAuditRows = countRows("T_accounts_AUD", "id", oldAccountId);
        long oldCredentialAuditRows = countRows("T_credentials_AUD", "account_id", oldAccountId);
        long oldRoleAuditRows = countRows("T_account_roles_AUD", "account_id", oldAccountId);
        assertEquals(0, oldAccountAuditRows, "Old account audit rows should be purged");
        assertEquals(0, oldCredentialAuditRows, "Old credential audit rows should be purged");
        assertEquals(0, oldRoleAuditRows, "Old role audit rows should be purged");

        // Verify recent account audit rows remain.
        long recentAccountAuditRows = countRows("T_accounts_AUD", "id", recentAccountId);
        long recentCredentialAuditRows = countRows("T_credentials_AUD", "account_id", recentAccountId);
        assertTrue(recentAccountAuditRows > 0, "Recent account audit rows should remain");
        assertTrue(recentCredentialAuditRows > 0, "Recent credential audit rows should remain");

        // Verify old REVINFO rows are gone but recent ones remain.
        long oldRevInfoRows = countNative(
                "SELECT COUNT(*) FROM REVINFO WHERE REVTSTMP = :ts", "ts", oldTimestamp);
        long recentRevInfoRows = countNative(
                "SELECT COUNT(*) FROM REVINFO WHERE REVTSTMP >= :ts", "ts",
                Instant.now().minus(1, ChronoUnit.HOURS).toEpochMilli());
        assertEquals(0, oldRevInfoRows, "Old REVINFO rows should be purged");
        assertTrue(recentRevInfoRows > 0, "Recent REVINFO rows should remain");
        transactionHelper.commitTransaction();
    }

    @Test
    public void testPurgeKeepsRecentAuditRows() throws Exception {
        // Create an account with recent audit rows only.
        transactionHelper.beginTransaction();
        Account account = accountService.createAccountForOrg(
                "recent2_" + System.currentTimeMillis() + "@example.com",
                "Recent Account 2",
                "recent2" + System.currentTimeMillis(),
                "Pass123",
                AccountService.NATIVE,
                getDefaultOrgId());
        String accountId = account.getId();
        transactionHelper.commitTransaction();

        // Run purge with a 90-day retention period.
        AuditPurgeService.AuditPurgeResult result = auditPurgeService.purgeAuditData(90);

        assertEquals(90, result.getRetentionDays());
        long deletedFromAuditTables = result.getDeletedByTable().values().stream()
                .mapToLong(v -> v.longValue()).sum();
        assertEquals(0, deletedFromAuditTables,
                "No recent audit rows should be deleted with a 90-day retention");
        assertEquals(0, result.getDeletedRevInfoCount(),
                "No recent REVINFO rows should be deleted");
        assertEquals(0, result.getTotalDeleted());

        // Verify the account audit rows remain.
        transactionHelper.beginTransaction();
        long accountAuditRows = countRows("T_accounts_AUD", "id", accountId);
        assertTrue(accountAuditRows > 0, "Recent account audit rows should remain");
        transactionHelper.commitTransaction();
    }

    private String getDefaultOrgId() {
        return (String) em.createNativeQuery("SELECT id FROM T_organisations LIMIT 1")
                .getSingleResult();
    }

    private long countRows(String table, String column, String value) {
        Query query = em.createNativeQuery("SELECT COUNT(*) FROM " + table + " WHERE " + column + " = :value");
        query.setParameter("value", value);
        return ((Number) query.getSingleResult()).longValue();
    }

    private long countNative(String sql, String paramName, Object paramValue) {
        Query query = em.createNativeQuery(sql);
        query.setParameter(paramName, paramValue);
        return ((Number) query.getSingleResult()).longValue();
    }
}
